endroid_qr_code:
    default:
        backgroundColor:
            - 100
            - 0
            - 0
        foregroundColor:
            - 0
            - 100
            - 0
        writer: Endroid\QrCode\Writer\SvgWriter
        size: 300
        margin: 10
        encoding: 'UTF-8'
        errorCorrectionLevel: 'low'
        roundBlockSizeMode: 'margin'
        validateResult: false
