security:
    encoders:
        App\Entity\Account\Account:
            algorithm: sodium
    providers:
        db:
            entity:
                class: App\Entity\Account\Account
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: db
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: '^/admin', roles: ROLE_ADMIN }


