security:
    encoders:
        App\Entity\Account\Account:
            algorithm: sodium
    providers:
        db:
            entity:
                class: App\Entity\Account\Account
    role_hierarchy:
        ROLE_ADMIN: ROLE_ORGA
        ROLE_ORGA: ROLE_CDP
        ROLE_CDP: ROLE_STAFF
        ROLE_STAFF: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: db
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
    access_control:
        - { path: '^/admin', roles: ROLE_STAFF }


